# Generated by terraform apply — infra/terraform/aws-classroom. Do not edit by hand;
# re-run `terraform apply` and this file is regenerated in place.

[web]
web1 ansible_host=${web_private_ip}

[db]
db1 ansible_host=${db_private_ip}

[web:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/keys/appointment-ec2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[db:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/ubuntu/keys/appointment-ec2.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
web_private_ip=${web_private_ip}
web_public_ip=${web_public_ip}
db_private_ip=${db_private_ip}
control_public_ip=${control_public_ip}
