name: Deploy to VPS

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/appointment
            
            # Pull latest changes
            git fetch origin
            git checkout main
            git pull origin main
            
            # Install backend dependencies
            cd backend
            npm ci --production
            
            # Install frontend dependencies and build
            cd ../frontend
            npm ci --production
            npm run build
            
            # Restart applications
            cd ..
            pm2 restart ecosystem.config.js --update-env
            
            # Show status
            pm2 status
            
            # Health check
            sleep 5
            curl -f http://localhost:5000/health || exit 1
            
      - name: Notify Success
        if: success()
        run: echo "✅ Deployment successful!"
        
      - name: Notify Failure
        if: failure()
        run: echo "❌ Deployment failed!"

