name: Simple Test Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Test
        run: |
          echo "🚀 Simple test workflow is running!"
          echo "✅ This proves GitHub Actions is working"
          echo "📅 Current time: $(date)"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "👤 Actor: ${{ github.actor }}"
